### PR TITLE
Event emitter "off" fix

### PR DESCRIPTION
**Pull request by cutandpastey**
Fixes https://github.com/guardian/scribe/issues/370

### CODE REVIEW

**Comment by cutandpastey** [comment]
@rrees Undo manager tests are failing?

**Comment by jamespamplin** [comment]
:+1: code looks fine

**Comment by hmgibson23** [comment]
Looks solid :+1:

**Comment by rrees** [comment]
@cutandpastey can you check what the value of lodash is in your bower.json. That's while the Circle build is failing.

**Comment by rrees** [comment]
@cutandpastey actually this is a transitive dependency, let me have a look at it

**Comment by rrees** [comment]
Yeah, my bad, indirectly. Due to the sanitizer dependency we need to merge #374 and then merge master to the branches that are failing the Circle build

**Pull request merged**
