### PR TITLE
Event emitter: make callbacks unique

### PR DESCRIPTION
**Pull request by rrees**
I've applied the Set idea I mentioned in #323 to the code here.

I wanted to do a bit more but I hit an issue with unit tests that I'll share on the mailing list.

### CODE REVIEW

**Comment by cutandpastey** [comment]
I did this here https://github.com/guardian/scribe/pull/323/files after the comments, thought you would get a notification :(

**Comment by rrees** [comment]
@cutandpastey Ah, I may have got the notifications but I may have missed it. At least the code is reassuring similar. I'll drop this PR.

**Comment by rrees** [comment]
@cutandpastey Actually having a look at the change I'm not sure it works because you don't rewrite the var references, however it will probably work with the test suite because we only add one callback to the event emitter

**Comment by rrees** [comment]
@cutandpastey Actually ignore me they both look the same

**Comment by cutandpastey** [comment]
You `clear()` the set.  Should I add this in or are we all good?

**Comment by hmgibson23** [comment]
The build also failed! Maybe run again?

**Comment by rrees** [comment]
@cutandpastey the idea with the clear is that the structure stays the same but empty

**Comment by cutandpastey** [comment]
Yeah, timeout issue :( have re-run.

**Comment by cutandpastey** [comment]
@rrees Oh, I thought this was for GC.

**Pull request merged**
