### PR TITLE
Fixing a bug caused when you automatically trigger focus

### PR DESCRIPTION
**Pull request by gja**
to scribe controlled DOM

How I'm triggering this:
```js
      var range = document.createRange();
      range.selectNodeContents(element);
      range.collapse(false);
      var selection = window.getSelection();
      selection.removeAllRanges();
      console.log(range);
      selection.addRange(range);
```

### CODE REVIEW

**Comment by hmgibson23** [comment]
This seems sane. Could you possibly make a jsbin with the bug reproduced?

**Comment by gja** [comment]
Is there an existing jsbin I can duplicate or something?

**Comment by rrees** [comment]
@gja This was one I found from an earlier issue:

http://jsfiddle.net/8g6ezbsb/3/

**Comment by hmgibson23** [comment]
@gja  - There is also this one from the brower inconsistencies file http://jsbin.com/iwEWUXo/2/edit?js,console,output

**Comment by gja** [comment]
Thanks, I've been a bit busy, but i'll create this later today

**Comment by hmgibson23** [comment]
Great. If you add to the browser inconsistencies file then we can keep track of it...

**Comment by rrees** [comment]
Closing as inactive.

**Pull request closed without merging**
